<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Daniel Felbah" />


<title>Reproducible Research: Peer Assessment 1</title>

<script src="PA1_template_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="PA1_template_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="PA1_template_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="PA1_template_files/navigation-1.1/tabsets.js"></script>
<link href="PA1_template_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="PA1_template_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Reproducible Research: Peer Assessment 1</h1>
<h4 class="author"><em>Daniel Felbah</em></h4>

</div>


<hr />
<div id="libraries-used" class="section level4">
<h4>Libraries used</h4>
<pre class="r"><code>library(dplyr)
library(lubridate)
library(ggplot2)
library(cowplot)</code></pre>
<p> </p>
</div>
<div id="loading-and-preprocessing-the-data" class="section level2">
<h2>Loading and preprocessing the data</h2>
<pre class="r"><code># Unzip file
unzip(&quot;activity.zip&quot;)

# Load the data (i.e. read.csv())
activity &lt;- read.csv(&quot;activity.csv&quot;, stringsAsFactors = FALSE)

# Process/transform the data (if necessary) into a format suitable for your analysis
activity &lt;- tbl_df(activity)
activity$date &lt;- ymd(activity$date)

str(activity)</code></pre>
<pre><code>## Classes &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;:    17568 obs. of  3 variables:
##  $ steps   : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ date    : Date, format: &quot;2012-10-01&quot; &quot;2012-10-01&quot; ...
##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...</code></pre>
<p> </p>
</div>
<div id="what-is-mean-total-number-of-steps-taken-per-day" class="section level2">
<h2>What is mean total number of steps taken per day?</h2>
<pre class="r"><code># Calculate the total number of steps taken per day
total_steps_by_day &lt;- summarise(group_by(activity, date), total_steps = sum(steps, na.rm = TRUE))
head(total_steps_by_day, 10)</code></pre>
<pre><code>## # A tibble: 10 x 2
##    date       total_steps
##    &lt;date&gt;           &lt;int&gt;
##  1 2012-10-01           0
##  2 2012-10-02         126
##  3 2012-10-03       11352
##  4 2012-10-04       12116
##  5 2012-10-05       13294
##  6 2012-10-06       15420
##  7 2012-10-07       11015
##  8 2012-10-08           0
##  9 2012-10-09       12811
## 10 2012-10-10        9900</code></pre>
<pre class="r"><code># Make a histogram of the total number of steps taken each day
qplot(total_steps, data = total_steps_by_day, main = &quot;Histogram of the total number of steps taken each day&quot;, binwidth = 1000)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-2-1.png" /><!-- --></p>
<pre class="r"><code># Calculate and report the mean and median of the total number of steps taken per day
summary(total_steps_by_day$total_steps)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0    6778   10395    9354   12811   21194</code></pre>
<p>The mean and median of the total number of steps taken per day are <code>9354</code> and <code>10395</code> respectively.</p>
<p> </p>
</div>
<div id="what-is-the-average-daily-activity-pattern" class="section level2">
<h2>What is the average daily activity pattern?</h2>
<pre class="r"><code># Make a time series plot (i.e. type=&quot;l&quot;) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

average_steps_by_interval &lt;- summarise(group_by(activity, interval), average_steps = mean(steps, na.rm = TRUE))

ggplot(average_steps_by_interval, aes(x=interval, y=average_steps)) + geom_line()</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-3-1.png" /><!-- --></p>
<p>Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?</p>
<p>Looking at the plot, it should be between <code>830</code> and <code>835</code></p>
</div>
<div id="imputing-missing-values" class="section level2">
<h2>Imputing missing values</h2>
<pre class="r"><code># Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

table(is.na(activity$steps))</code></pre>
<pre><code>## 
## FALSE  TRUE 
## 15264  2304</code></pre>
<p>There are <code>2304</code> NAs in the dataset.</p>
<p>Since there are so many NAs in the dataset, we’ll replace each NA with the mean number of steps for that interval across the days.<br />
We have <code>average_steps_by_interval</code> already created in the table so we’ll map it back to the main dataset to replace all NA’s. We will call this new data <code>activity_NAs_replaced</code>.</p>
<pre class="r"><code># Create a new dataset that is equal to the original dataset but with the missing data filled in.

activity_NAs_replaced &lt;- activity # make a copy of original file

for (i in 1:nrow(activity)) {  # loop through activity
  
  if (is.na(activity$steps[i])){  # check if steps is NA
    
    activity_NAs_replaced$steps[i] &lt;- average_steps_by_interval[which(average_steps_by_interval$interval == activity$interval[i]),]$average_steps  # replace NA
  
  }
  
}

table(is.na(activity_NAs_replaced$steps)) # check if there are still NAs</code></pre>
<pre><code>## 
## FALSE 
## 17568</code></pre>
<p>Make a histogram of the total number of steps taken each day.</p>
<pre class="r"><code># Calculate the total number of steps taken per day
total_steps_by_day_new &lt;- summarise(group_by(activity_NAs_replaced, date), total_steps = sum(steps))


# Make a histogram of the total number of steps taken each day
new &lt;- qplot(total_steps, data = total_steps_by_day_new, main = &quot;Data without NAs&quot;, binwidth = 1000)
old &lt;- qplot(total_steps, data = total_steps_by_day, main = &quot;Data with NAs&quot;, binwidth = 1000)

plot_grid(new, old)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-6-1.png" /><!-- --></p>
<p>Calculate and report the mean and median total number of steps taken per day.</p>
<pre class="r"><code>summary(total_steps_by_day_new$total_steps)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      41    9819   10766   10766   12811   21194</code></pre>
<p>The mean and median of the total number of steps taken per day are <code>10766</code> and <code>10766</code> respectively.</p>
</div>
<div id="are-there-differences-in-activity-patterns-between-weekdays-and-weekends" class="section level2">
<h2>Are there differences in activity patterns between weekdays and weekends?</h2>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
